### ISSUE TITLE
Add support for region

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/terraform-provider-scalingo#11]
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/25630977144

User should configure the provider with a parameter like `region = "osc-fr1"` then the provider query the relevant API

**Comment by EtienneM** [comment]
@Soulou it seems like this issue is already solved, doesn't it?

**Comment by Soulou** [comment]
Yes it is
