### ISSUE TITLE
[Resource SCMRepoLink][Bug] The app fields "must be replaced" after an import

### ISSUE THREAD

**Issue by josephpage** [Scalingo/terraform-provider-scalingo#153]
### Description of the bug

After importing a `scalingo_scm_repo_link` resource, Terraform want to change its `id` and `app` property fields, forcing the deletion/creation of the resource, which seems unexpected.

### What is expected

After an import, only the property fields can be replaced, not the property fields that are used to identify the resource.

### How to reproduce :
```tf
resource "scalingo_scm_repo_link" "github" {
  app    = scalingo_app.my-app.name
  ...
}
```

```shell
$ terraform import scalingo_scm_repo_link.github my-app

# => Import successful!

$ terraform plan

...

  # scalingo_scm_repo_link.github must be replaced
-/+ resource "scalingo_scm_repo_link" "github" {
      ~ app                          = "xxxxxxxxxxxxxxxxxxxxxxxx" -> "my-app" # forces replacement
      ~ id                           = "xxxxxxxxxxxxxxxxxxxxxxxx" -> (known after apply)
        # (9 unchanged attributes hidden)
    }

...
```

**Comment by Soulou** [comment]
Hi @josephpage,

We tried to reproduce your issue without success, the `scm_repo_link` resource is never destroyed/recreated, always update in-place.

Can you maybe contact our support to give more details about your terraform output, and the precise commands you're trying to get. (to prevent making the info public?

Thanks a lot.

**Comment by josephpage** [comment]
I will contact support as I am reproducing the exact same bug with another application.

I suspect the problem comes from this line ([`scalingo/resource_scalingo_scm_repo_link.go`](https://github.com/Scalingo/terraform-provider-scalingo/blob/f9a3fa61432fcb83755dbc5fe7e3ebc7de6bed38/scalingo/resource_scalingo_scm_repo_link.go#LL234C49-L234C54)) which associates the AppID with the `app` attribute in the state, which is, on the one hand, contrary to the documentation and, on the other hand, does not correspond to what I think is meant for this attribute (as the id being already assigned to the `id` attribute)

**Comment by josephpage** [comment]
Finally I found a workaround. Instead of : 

```
resource "scalingo_app" "app" {
  name = var.name
  [...]
}

resource "scalingo_scm_repo_link" "scm_repo_link" {
  app = scalingo_app.app.name
  [...]
```

I changed the `.name` to `.id` : 

```
resource "scalingo_app" "app" {
  name = var.name
  [...]
}

resource "scalingo_scm_repo_link" "scm_repo_link" {
  app = scalingo_app.app.id
  [...]
```

And I don't have the problem anymore!

But this suggests that there is a problem and that you have to :
- either modify the documentation : "ID or slug name of the targeted application" => "ID of the targeted application
- or store the slug name in the app attribute of the state instead of the ID (if we modify the code it will force replacement for all resources `scalingo_scm_repo_link` already existing in the states of users)

**Comment by Soulou** [comment]
Thanks a lot for your analysis. 

It has been decided to clarify the documentation, in all app sub-resources, we're actually expecting/recommending an app_id.

https://github.com/Scalingo/terraform-provider-scalingo/pull/171
