### ISSUE TITLE
It should be possible to define the formation of an application

### ISSUE THREAD

**Issue by Soulou** [Scalingo/terraform-provider-scalingo#2]
```
resource "scalingo_app" "default" {
  name = "my-app"
  containers {
    name = "web"
    amount = 5
    size = "L"
  }
  containers {
    name = "worker"
    amount = 2
    size = "M" 
  }
}
```

If I remember correctly a `schema.TypeSet` has to be used to use this syntax.

**Comment by EtienneM** [comment]
Inspiration pour implémenter la propriété "containers": (voir egress/igress)
https://github.com/Scalingo/scalingo-outscale-terraform/blob/master/secgroups.tf
https://github.com/remijouannet/terraform-provider-osc/blob/master/osc/resource_osc_security_group.go

**Comment by EtienneM** [comment]
After some work along with @johnsudaar, maybe this is not the best solution to embed the formation in the app. We propose to have a separate resource for the formation (like Heroku). Actually, if we embed it, it makes the App resource code more complicated. Moreover, then we should also embed almost everything as everything depends on an app: domains, notifications... and the App resource code will be event more complicated. Most of the providers will not embed resource like that.

What do you think about:

```yml
resource "scalingo_app" "default" {
  name = "my-app"
  ...
}

resource "scalingo_formation" "web" {
  amount = 5
  size = "L"
  app_id = "${scalingo_app.default.id}"
}

resource "scalingo_formation" "worker" {
  amount = 5
  size = "L"
  app_id = "${scalingo_app.default.id}"
}
```

For the autoscaler we could write:

```yml
resource "scalingo_formation" "worker" {
  autoscaler {
    from = 1
    to = 5
    metrics = "ram"
    target = "60"
  }
  size = "L"
  app_id = "${scalingo_app.default.id}"
}
```

**Comment by Soulou** [comment]
I'm not strongly opposed to the idea but your argument is wrong. "If we embed this we have to embed almost everything" 

Domains, Collaborators etc are CRUD resources which work really well at the Terraform level, you give oarams, create something with an ID etc.

The formation is configuration, There is nothing like a CRUD resource, it's just some settings to the app. To me it's a major difference.

But I get your point and if you think this API is better, go for it.

**Comment by Soulou** [comment]
Do we want to call it formation as we mostly name this resource container_type?

**Comment by EtienneM** [comment]
Another point we had with @johnsudaar is that we don't have a lot of perspective on the technology and are not fully aware of all the outcome of a choice. There is a part of _guts feeling_ in this new proposition of syntax. 

I will try this and let you know if I was mistaken... ^^

You're right, formation is not a good choice in our context. We only talk about container types.

**Comment by EtienneM** [comment]
I actually like your point about the other things being CRUD resources and not the formation... I'm all confused now ^^

**Comment by Soulou** [comment]
Heroku provider has a separate resource, so let’s say they know what they are doing ?

-- Léo Unbekandt
